# gst/migrations/0001_initial.py
# Generated by Django 5.0.7 on 2024-07-23 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=0)),
                ('gst_type', models.CharField(choices=[('IGST', 'Integrated GST'), ('CGST_SGST', 'Central GST + State GST')], default='IGST', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(help_text='Harmonized System of Nomenclature code', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2,8}$', message='HSN must be between 2 to 8 digits')])),
            ],
        ),
    ]
