# Generated by Django 5.0.7 on 2024-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gst',
            name='gst_type',
        ),
        migrations.AlterField(
            model_name='gst',
            name='percentage',
            field=models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=12),
        ),
    ]
