# Generated by Django 5.0.7 on 2024-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_remove_gst_gst_type_alter_gst_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='percentage',
            field=models.FloatField(choices=[(0.0, '0%'), (5.0, '5%'), (12.0, '12%'), (18.0, '18%'), (28.0, '28%')], unique=True),
        ),
    ]
