# gst/migrations/0004_alter_hsn_hsn_code.py
# Generated by Django 5.0.7 on 2024-07-31 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0003_alter_gst_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsn',
            name='hsn_code',
            field=models.CharField(help_text='Harmonized System of Nomenclature code', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2,8}$', message='HSN must be between 2 to 8 digits')]),
        ),
    ]
