# Generated by Django 5.1.1 on 2024-09-15 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0007_statecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(unique=True)),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='gst',
            name='percentage',
        ),
        migrations.AddField(
            model_name='gst',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gst.gstrate'),
        ),
    ]
