# Generated by Django 5.1.1 on 2024-09-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0008_gstrate_remove_gst_percentage_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='rate',
            field=models.ForeignKey(default=12.0, on_delete=django.db.models.deletion.CASCADE, to='gst.gstrate'),
            preserve_default=False,
        ),
    ]
