# item/migrations/0001_initial.py
# Generated by Django 5.0.7 on 2024-07-23 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_alter_medicalrepresentative_mobile_number'),
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{0,10}$', 'SKU must be between 0 to 10 digits')])),
                ('image', models.ImageField(upload_to='item_images/')),
                ('sold_loose', models.BooleanField(default=False)),
                ('sold_online', models.BooleanField(default=False)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('use', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_form', models.CharField(max_length=100)),
                ('packing', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('prescription_required', models.BooleanField(default=True)),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_medicine', to='gst.gst')),
                ('hsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_medicine', to='gst.hsn')),
                ('marketed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketed_items_medicine', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonMedicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{0,10}$', 'SKU must be between 0 to 10 digits')])),
                ('image', models.ImageField(upload_to='item_images/')),
                ('sold_loose', models.BooleanField(default=False)),
                ('sold_online', models.BooleanField(default=False)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landing_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('use', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_nonmedicalitem', to='gst.gst')),
                ('hsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_nonmedicalitem', to='gst.hsn')),
                ('marketed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketed_items_nonmedicalitem', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
