# Generated by Django 5.0.7 on 2024-07-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_medicine_created_at_medicine_updated_at_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='medicine',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='medicine',
        #     name='updated_at',
        # ),
        # migrations.RemoveField(
        #     model_name='nonmedicalitem',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='nonmedicalitem',
        #     name='updated_at',
        # ),
    ]
