# Generated by Django 5.0.7 on 2024-07-28 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_medicine_created_at_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='medicine',
        #     name='created_at',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='medicine',
        #     name='updated_at',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='nonmedicalitem',
        #     name='created_at',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='nonmedicalitem',
        #     name='updated_at',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
    ]
