# item/migrations/0008_remove_medicine_created_at_and_more.py
# Generated by Django 5.0.7 on 2024-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_remove_nonmedicalitem_created_at_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='medicine',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='medicine',
        #     name='updated_at',
        # ),
    ]
