# item/migrations/0014_rename_marketed_by_medicine_company_and_more.py
# Generated by Django 5.0.7 on 2024-07-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_medicalrepresentative_mobile_number'),
        ('item', '0013_medicine_type_nonmedicalitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='marketed_by',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='nonmedicalitem',
            old_name='marketed_by',
            new_name='company',
        ),
        migrations.AddField(
            model_name='medicine',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.division'),
        ),
        migrations.AddField(
            model_name='nonmedicalitem',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.division'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='type',
            field=models.CharField(default='item_medicine', max_length=50),
        ),
        migrations.AlterField(
            model_name='nonmedicalitem',
            name='type',
            field=models.CharField(default='item_medicine', max_length=50),
        ),
    ]
