# Generated by Django 5.0.7 on 2024-07-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_remove_medicine_type_remove_nonmedicalitem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(default='medicine', max_length=50),
        ),
        migrations.AddField(
            model_name='nonmedicalitem',
            name='type',
            field=models.CharField(default='nonmedicalitem', max_length=50),
        ),
    ]
