# Generated by Django 5.0.7 on 2024-07-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hsn',
        ),
    ]
