# Generated by Django 5.0.7 on 2024-07-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_address_line1_alter_customer_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(default='Vora', max_length=100),
        ),
    ]
