# customer/migrations/0008_alter_customer_title.py
# Generated by Django 5.0.7 on 2024-07-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_firm_name_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Master', 'Master'), ('Adv.', 'Advocate'), ('Dr.', 'Doctor'), ('M/s', 'Messrs'), ('Prof.', 'Professor')], max_length=10, null=True),
        ),
    ]
