# Generated by Django 5.0.7 on 2024-07-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
