# Generated by Django 5.1.1 on 2024-09-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
