# Generated by Django 5.1.1 on 2024-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='status',
            new_name='current_status',
        ),
    ]
