# purchase/migrations/0002_remove_purchaseitem_gst_percentage_and_more.py
# Generated by Django 5.0.7 on 2024-08-01 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('supplier', '0009_rename_drug_license_validity_supplier_drug_license1_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='gst_percentage',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
