# purchase/migrations/0003_remove_purchase_supplier_name.py
# Generated by Django 5.0.7 on 2024-08-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchaseitem_gst_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier_name',
        ),
    ]
