# purchase/migrations/0005_purchaseitem_gst.py
# Generated by Django 5.0.7 on 2024-08-03 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0006_delete_hsn'),
        ('purchase', '0004_purchase_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='gst',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='gst.gst'),
            preserve_default=False,
        ),
    ]
