# Generated by Django 5.0.7 on 2024-08-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseitem_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='gst',
        ),
    ]
