# Generated by Django 5.1.1 on 2024-09-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_purchaseitem_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(max_length=50),
        ),
    ]
