# company/migrations/0003_alter_division_medical_representative.py
# Generated by Django 5.0.7 on 2024-07-13 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_division_medical_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='medical_representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='company.medicalrepresentative'),
        ),
    ]
