# Generated by Django 5.0.7 on 2024-07-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_name_alter_division_unique_together'),
        ('supplier', '0009_rename_drug_license_validity_supplier_drug_license1_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='medical_representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.medicalrepresentative'),
        ),
        migrations.AddField(
            model_name='company',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='companies', to='supplier.supplier'),
        ),
    ]
