# company/migrations/0006_alter_medicalrepresentative_mobile_number.py
# Generated by Django 5.0.7 on 2024-07-21 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_medical_representative_company_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Only numeric characters are allowed.')]),
        ),
    ]
