# Generated by Django 5.0.7 on 2024-07-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_alter_supplier_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
    ]
