# supplier/migrations/0009_rename_drug_license_validity_supplier_drug_license1_validity.py
# Generated by Django 5.0.7 on 2024-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_remove_supplier_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='drug_license_validity',
            new_name='drug_license1_validity',
        ),
    ]
