# Generated by Django 5.1.1 on 2024-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_rename_drug_license_validity_supplier_drug_license1_validity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='status',
            new_name='current_status',
        ),
    ]
